use master
go
IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = 'Crypto_DB')
	DROP DATABASE Crypto_DB
go
Create database Crypto_DB
go
use Crypto_DB
go
set dateformat DMY
go
use crypto_db
go
--
CREATE MASTER KEY -- 
ENCRYPTION BY PASSWORD = 'PASSWORD@123'
GO

CREATE CERTIFICATE Certificado
ENCRYPTION BY PASSWORD = 'SENHA@123'
WITH SUBJECT = 'Certificado Senha Usuario'
GO

CREATE SYMMETRIC KEY ChaveSenha
WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE Certificado --
GO
CREATE TABLE Usuario
(
   ID INT IDENTITY,
   [LOGIN] VARCHAR(MAX),
   SENHA VARBINARY (MAX)
)
GO
OPEN SYMMETRIC KEY ChaveSenha
DECRYPTION BY CERTIFICATE Certificado WITH PASSWORD = 'SENHA@123'

DECLARE @GUID UNIQUEIDENTIFIER = (SELECT KEY_GUID('ChaveSenha'))
INSERT INTO Usuario VALUES ('LUIZ', ENCRYPTBYKEY(@GUID, 'luiz123'))
GO

SELECT    * FROM Usuario

CLOSE SYMMETRIC KEY ChaveSenha

select * from Usuario

OPEN SYMMETRIC KEY ChaveSenha
DECRYPTION BY CERTIFICATE Certificado  WITH PASSWORD = 'SENHA@123'
GO

SELECT    *
,   senhadescriptografada = CAST (DECRYPTBYKEY(SENHA) AS varchar(50))
FROM      Usuario
GO

CLOSE SYMMETRIC KEY ChaveSenha